2024-03-08 12:21:37,778 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 12:21:37,832 INFO: User found: tommyboy [in users.py:101]
2024-03-08 12:21:37,833 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 12:21:37,915 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 12:21:37,915 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-08 12:29:36,363 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 12:29:36,364 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 12:29:36,370 INFO: User found: tommyboy [in users.py:101]
2024-03-08 12:29:36,370 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 12:29:36,481 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 12:29:36,481 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-08 12:29:59,126 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 12:29:59,126 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 12:29:59,130 INFO: User found: tommyboy [in users.py:101]
2024-03-08 12:29:59,131 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 12:29:59,240 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 12:29:59,241 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-08 12:30:44,426 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 12:30:44,427 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 12:30:44,431 INFO: User found: tommyboy [in users.py:101]
2024-03-08 12:30:44,432 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 12:30:44,536 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 12:30:44,536 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-08 12:31:59,974 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-08 12:32:13,274 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 12:32:13,276 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 12:32:13,333 INFO: User found: tommyboy [in users.py:101]
2024-03-08 12:32:13,333 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 12:32:13,419 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 12:32:13,420 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-08 12:33:09,113 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 12:33:09,114 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 12:33:09,120 INFO: User found: eminem [in users.py:101]
2024-03-08 12:33:09,120 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-08 12:33:09,230 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-08 12:33:09,231 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-08 13:04:14,271 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-08 13:04:33,704 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:04:33,705 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:04:33,765 INFO: User found: tommyboy [in users.py:101]
2024-03-08 13:04:33,766 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 13:04:33,850 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 13:04:33,851 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-08 13:05:32,933 INFO: Printing the data: {'email': 'brad@mail.com', 'username': 'brad', 'password': 'Superuser1'} [in users.py:51]
2024-03-08 13:05:32,934 INFO: Validation successful. Validated data: {'username': 'brad', 'email': 'brad@mail.com', 'password': 'Superuser1'} [in users.py:57]
2024-03-08 13:05:33,041 INFO: Printing the new user: <User brad> [in users.py:62]
2024-03-08 13:05:33,054 INFO: User added to db: <User brad> [in users.py:64]
2024-03-08 13:05:40,303 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:05:40,304 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:05:40,305 INFO: User found: brad [in users.py:101]
2024-03-08 13:05:40,305 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:05:40,379 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:05:40,380 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:06:20,588 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:06:20,589 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:06:20,592 INFO: User found: brad [in users.py:101]
2024-03-08 13:06:20,592 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:06:20,674 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:06:20,674 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:06:53,110 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:06:53,110 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:06:53,112 INFO: User found: eminem [in users.py:101]
2024-03-08 13:06:53,112 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-08 13:06:53,212 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-08 13:06:53,213 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-08 13:08:49,403 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:08:49,406 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:08:49,417 INFO: User found: brad [in users.py:101]
2024-03-08 13:08:49,418 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:08:49,514 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:08:49,515 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:10:53,121 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:10:53,121 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:10:53,124 INFO: User found: eminem [in users.py:101]
2024-03-08 13:10:53,124 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-08 13:10:53,228 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-08 13:10:53,228 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-08 13:23:34,048 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-08 13:23:53,767 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:23:53,768 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:23:53,819 INFO: User found: tommyboy [in users.py:101]
2024-03-08 13:23:53,819 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-08 13:23:53,936 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-08 13:23:53,937 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-08 13:24:52,768 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:24:52,769 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:24:52,773 INFO: User found: brad [in users.py:101]
2024-03-08 13:24:52,773 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:24:52,915 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:24:52,916 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:26:03,509 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-08 13:26:15,784 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:26:15,785 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:26:15,876 INFO: User found: brad [in users.py:101]
2024-03-08 13:26:15,877 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:26:16,028 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:26:16,029 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:27:08,404 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:27:08,405 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:27:08,408 INFO: User found: brad [in users.py:101]
2024-03-08 13:27:08,408 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:27:08,546 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:27:08,548 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:28:19,830 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:28:19,834 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:28:19,868 INFO: User found: brad [in users.py:101]
2024-03-08 13:28:19,869 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:28:20,017 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:28:20,018 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:29:19,123 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:29:19,124 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:29:19,126 INFO: User found: brad [in users.py:101]
2024-03-08 13:29:19,127 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:29:19,237 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:29:19,238 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:31:23,080 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:31:23,082 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:31:23,087 INFO: User found: brad [in users.py:101]
2024-03-08 13:31:23,088 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:31:23,185 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:31:23,186 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:31:50,557 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:31:50,559 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:31:50,564 INFO: User found: brad [in users.py:101]
2024-03-08 13:31:50,564 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:31:50,680 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:31:50,680 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:36:00,803 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:36:00,805 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:36:00,815 INFO: User found: brad [in users.py:101]
2024-03-08 13:36:00,816 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:36:00,916 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:36:00,917 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:36:53,170 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:36:53,171 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:36:53,173 INFO: User found: brad [in users.py:101]
2024-03-08 13:36:53,173 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:36:53,306 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:36:53,307 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:40:09,164 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:40:09,166 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:40:09,177 INFO: User found: brad [in users.py:101]
2024-03-08 13:40:09,177 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:40:09,282 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:40:09,283 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:43:25,463 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:43:25,465 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:43:25,471 INFO: User found: brad [in users.py:101]
2024-03-08 13:43:25,471 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:43:25,560 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:43:25,561 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:50:13,832 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:50:13,834 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:50:13,838 INFO: User found: brad [in users.py:101]
2024-03-08 13:50:13,839 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:50:13,947 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:50:13,947 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:50:34,100 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:50:34,101 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:50:34,103 INFO: User found: eminem [in users.py:101]
2024-03-08 13:50:34,103 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-08 13:50:34,217 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-08 13:50:34,217 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-08 13:58:58,870 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:58:58,872 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:58:58,885 INFO: User found: brad [in users.py:101]
2024-03-08 13:58:58,885 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:58:58,989 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:58:58,990 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 13:59:34,062 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 13:59:34,063 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 13:59:34,067 INFO: User found: brad [in users.py:101]
2024-03-08 13:59:34,067 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 13:59:34,176 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 13:59:34,177 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 15:24:42,924 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-08 15:24:59,457 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 15:24:59,458 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 15:24:59,516 INFO: User found: brad [in users.py:101]
2024-03-08 15:24:59,516 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 15:24:59,602 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 15:24:59,603 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-08 15:26:28,265 INFO: Printing the data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:87]
2024-03-08 15:26:28,266 INFO: Validation successful. Validated data: {'username': 'brad', 'password': 'Superuser1'} [in users.py:93]
2024-03-08 15:26:28,272 INFO: User found: brad [in users.py:101]
2024-03-08 15:26:28,273 INFO: Attempting to validate password for user: brad [in users.py:108]
2024-03-08 15:26:28,382 INFO: Login successful for user: brad. Generating access token... [in users.py:116]
2024-03-08 15:26:28,383 INFO: Printing the response: <Response 479 bytes [200 OK]> [in users.py:129]
2024-03-10 12:15:13,720 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-10 12:27:40,502 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-10 12:45:46,545 INFO: Printing the data: {'email': 'nacho@mail.com', 'username': 'nachoman', 'password': 'Superuser1'} [in users.py:51]
2024-03-10 12:45:46,546 INFO: Validation successful. Validated data: {'username': 'nachoman', 'email': 'nacho@mail.com', 'password': 'Superuser1'} [in users.py:57]
2024-03-10 12:45:46,680 INFO: Printing the new user: <User nachoman> [in users.py:62]
2024-03-10 12:45:46,694 INFO: User added to db: <User nachoman> [in users.py:64]
2024-03-10 12:45:58,811 INFO: Printing the data: {'username': 'nachoman', 'password': 'Superuser1'} [in users.py:87]
2024-03-10 12:45:58,812 INFO: Validation successful. Validated data: {'username': 'nachoman', 'password': 'Superuser1'} [in users.py:93]
2024-03-10 12:45:58,826 INFO: User found: nachoman [in users.py:101]
2024-03-10 12:45:58,826 INFO: Attempting to validate password for user: nachoman [in users.py:108]
2024-03-10 12:45:58,980 INFO: Login successful for user: nachoman. Generating access token... [in users.py:116]
2024-03-10 12:45:58,982 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-11 16:13:20,284 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-11 16:13:28,114 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-11 16:13:28,116 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-11 16:13:28,179 INFO: User found: tommyboy [in users.py:101]
2024-03-11 16:13:28,180 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-11 16:13:28,284 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-11 16:13:28,285 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-12 10:10:46,858 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-12 10:26:47,470 INFO: Printing the data: {'email': 'felon@mail.com', 'username': 'trump', 'password': 'superuser1'} [in users.py:51]
2024-03-12 10:26:47,472 INFO: Validation successful. Validated data: {'username': 'trump', 'email': 'felon@mail.com', 'password': 'superuser1'} [in users.py:57]
2024-03-12 10:26:47,607 INFO: Printing the new user: <User trump> [in users.py:62]
2024-03-12 10:26:47,631 INFO: User added to db: <User trump> [in users.py:64]
2024-03-12 10:31:47,169 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-12 10:31:47,170 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-12 10:31:47,180 INFO: User found: tommyboy [in users.py:101]
2024-03-12 10:31:47,181 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-12 10:31:47,295 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-12 10:31:47,296 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-12 10:32:12,991 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-12 10:32:12,991 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-12 10:32:12,994 INFO: User found: tommyboy [in users.py:101]
2024-03-12 10:32:12,994 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-12 10:32:13,095 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-12 10:32:13,095 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-12 10:33:03,749 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-12 10:33:20,464 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-12 10:33:20,465 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-12 10:33:20,496 INFO: User found: tommyboy [in users.py:101]
2024-03-12 10:33:20,496 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-12 10:33:20,574 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-12 10:33:20,575 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-12 10:37:34,561 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-12 10:37:34,562 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-12 10:37:34,565 INFO: User found: tommyboy [in users.py:101]
2024-03-12 10:37:34,565 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-12 10:37:34,674 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-12 10:37:34,674 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-12 11:29:08,616 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-12 11:29:08,619 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-12 11:29:08,628 INFO: User found: tommyboy [in users.py:101]
2024-03-12 11:29:08,628 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-12 11:29:08,736 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-12 11:29:08,737 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-12 11:31:43,113 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-12 11:31:43,114 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-12 11:31:43,117 INFO: User found: tommyboy [in users.py:101]
2024-03-12 11:31:43,118 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-12 11:31:43,220 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-12 11:31:43,221 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-12 11:31:53,016 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-12 11:32:09,271 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-12 11:32:09,272 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-12 11:32:09,326 INFO: User found: tommyboy [in users.py:101]
2024-03-12 11:32:09,326 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-12 11:32:09,422 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-12 11:32:09,422 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-12 11:32:48,491 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-12 11:32:48,492 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-12 11:32:48,495 INFO: User found: tommyboy [in users.py:101]
2024-03-12 11:32:48,495 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-12 11:32:48,600 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-12 11:32:48,601 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-12 11:33:00,585 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-12 11:33:13,942 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-12 11:33:13,944 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-12 11:33:13,998 INFO: User found: tommyboy [in users.py:101]
2024-03-12 11:33:13,998 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-12 11:33:14,082 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-12 11:33:14,082 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-12 13:03:57,086 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-12 13:04:10,755 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-12 13:04:10,756 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-12 13:04:10,803 INFO: User found: tommyboy [in users.py:101]
2024-03-12 13:04:10,803 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-12 13:04:10,904 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-12 13:04:10,904 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-12 13:20:10,254 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-12 13:54:26,952 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-12 13:54:26,954 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-12 13:54:27,019 INFO: User found: tommyboy [in users.py:101]
2024-03-12 13:54:27,019 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-12 13:54:27,124 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-12 13:54:27,126 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-12 14:33:47,216 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-12 14:33:47,219 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-12 14:33:47,231 INFO: User found: tommyboy [in users.py:101]
2024-03-12 14:33:47,231 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-12 14:33:47,330 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-12 14:33:47,331 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-12 14:36:43,560 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-12 14:36:43,563 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-12 14:36:43,575 INFO: User found: tommyboy [in users.py:101]
2024-03-12 14:36:43,575 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-12 14:36:43,672 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-12 14:36:43,673 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-12 14:38:50,372 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-12 14:38:50,374 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-12 14:38:50,377 INFO: User found: tommyboy [in users.py:101]
2024-03-12 14:38:50,378 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-12 14:38:50,482 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-12 14:38:50,482 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-12 17:44:27,470 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-12 17:49:24,918 INFO: Printing the data: {'email': 'newguy@mail.com', 'username': 'new_guy2024', 'password': 'Superuser1'} [in users.py:51]
2024-03-12 17:49:24,922 INFO: Validation successful. Validated data: {'username': 'new_guy2024', 'email': 'newguy@mail.com', 'password': 'Superuser1'} [in users.py:57]
2024-03-12 17:49:25,061 INFO: Printing the new user: <User new_guy2024> [in users.py:62]
2024-03-12 17:49:25,084 INFO: User added to db: <User new_guy2024> [in users.py:64]
2024-03-12 17:49:35,214 INFO: Printing the data: {'username': 'new_guy2024', 'password': 'Superuser1'} [in users.py:87]
2024-03-12 17:49:35,215 INFO: Validation successful. Validated data: {'username': 'new_guy2024', 'password': 'Superuser1'} [in users.py:93]
2024-03-12 17:49:35,227 INFO: User found: new_guy2024 [in users.py:101]
2024-03-12 17:49:35,228 INFO: Attempting to validate password for user: new_guy2024 [in users.py:108]
2024-03-12 17:49:35,342 INFO: Login successful for user: new_guy2024. Generating access token... [in users.py:116]
2024-03-12 17:49:35,342 INFO: Printing the response: <Response 491 bytes [200 OK]> [in users.py:129]
2024-03-13 12:15:06,965 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-13 12:15:55,378 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-13 12:15:55,378 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-13 12:15:55,415 INFO: User found: tommyboy [in users.py:101]
2024-03-13 12:15:55,415 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-13 12:15:55,515 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-13 12:15:55,519 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-13 13:59:46,107 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-13 21:45:04,209 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-13 21:45:26,421 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-13 21:45:26,422 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-13 21:45:26,475 INFO: User found: eminem [in users.py:101]
2024-03-13 21:45:26,475 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-13 21:45:26,559 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-13 21:45:26,560 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-14 11:38:27,719 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-14 11:40:15,951 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-14 11:40:15,952 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-14 11:40:15,988 INFO: User found: eminem [in users.py:101]
2024-03-14 11:40:15,988 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-14 11:40:16,076 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-14 11:40:16,077 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-18 10:32:41,413 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-18 10:34:55,545 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 10:34:55,546 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 10:34:55,609 INFO: User found: eminem [in users.py:101]
2024-03-18 10:34:55,609 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-18 10:34:55,690 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-18 10:34:55,690 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-18 10:36:40,123 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-18 10:36:54,704 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 10:36:54,704 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 10:36:54,731 INFO: User found: eminem [in users.py:101]
2024-03-18 10:36:54,731 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-18 10:36:54,808 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-18 10:36:54,808 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-18 10:38:10,547 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 10:38:10,548 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 10:38:10,553 INFO: User found: tommyboy [in users.py:101]
2024-03-18 10:38:10,553 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 10:38:10,658 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 10:38:10,658 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 10:38:57,734 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 10:38:57,735 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 10:38:57,739 INFO: User found: tommyboy [in users.py:101]
2024-03-18 10:38:57,739 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 10:38:57,846 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 10:38:57,847 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 10:39:47,118 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 10:39:47,118 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 10:39:47,121 INFO: User found: tommyboy [in users.py:101]
2024-03-18 10:39:47,121 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 10:39:47,214 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 10:39:47,215 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 10:42:51,046 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 10:42:51,047 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 10:42:51,050 INFO: User found: tommyboy [in users.py:101]
2024-03-18 10:42:51,050 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 10:42:51,152 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 10:42:51,153 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 10:45:03,737 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 10:45:03,739 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 10:45:03,745 INFO: User found: tommyboy [in users.py:101]
2024-03-18 10:45:03,745 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 10:45:03,845 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 10:45:03,846 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 10:45:31,400 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 10:45:31,401 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 10:45:31,404 INFO: User found: tommyboy [in users.py:101]
2024-03-18 10:45:31,404 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 10:45:31,508 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 10:45:31,509 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 10:46:02,938 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 10:46:02,939 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 10:46:02,941 INFO: User found: tommyboy [in users.py:101]
2024-03-18 10:46:02,941 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 10:46:03,036 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 10:46:03,036 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 10:46:41,575 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 10:46:41,576 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 10:46:41,580 INFO: User found: tommyboy [in users.py:101]
2024-03-18 10:46:41,580 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 10:46:41,685 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 10:46:41,685 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 10:47:08,924 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 10:47:08,925 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 10:47:08,928 INFO: User found: tommyboy [in users.py:101]
2024-03-18 10:47:08,928 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 10:47:09,033 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 10:47:09,034 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 10:47:34,344 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 10:47:34,346 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 10:47:34,350 INFO: User found: tommyboy [in users.py:101]
2024-03-18 10:47:34,350 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 10:47:34,456 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 10:47:34,457 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 10:48:27,083 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 10:48:27,084 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 10:48:27,088 INFO: User found: tommyboy [in users.py:101]
2024-03-18 10:48:27,088 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 10:48:27,189 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 10:48:27,189 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 10:49:05,575 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 10:49:05,576 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 10:49:05,578 INFO: User found: tommyboy [in users.py:101]
2024-03-18 10:49:05,578 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 10:49:05,681 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 10:49:05,682 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 10:57:49,751 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-18 10:58:14,412 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 10:58:14,415 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 10:58:14,465 INFO: User found: tommyboy [in users.py:101]
2024-03-18 10:58:14,465 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 10:58:14,549 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 10:58:14,550 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 11:15:12,608 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 11:15:12,610 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 11:15:12,617 INFO: User found: tommyboy [in users.py:101]
2024-03-18 11:15:12,617 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 11:15:12,726 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 11:15:12,727 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 11:16:51,825 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 11:16:51,827 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 11:16:51,829 INFO: User found: tommyboy [in users.py:101]
2024-03-18 11:16:51,829 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 11:16:51,911 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 11:16:51,912 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 11:17:13,379 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 11:17:13,381 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 11:17:13,385 INFO: User found: tommyboy [in users.py:101]
2024-03-18 11:17:13,386 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 11:17:13,494 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 11:17:13,495 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 11:31:37,042 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 11:31:37,046 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 11:31:37,068 INFO: User found: tommyboy [in users.py:101]
2024-03-18 11:31:37,068 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 11:31:37,165 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 11:31:37,166 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 11:32:05,697 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 11:32:05,699 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 11:32:05,703 INFO: User found: eminem [in users.py:101]
2024-03-18 11:32:05,703 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-18 11:32:05,805 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-18 11:32:05,806 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-18 11:40:31,348 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 11:40:31,350 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 11:40:31,354 INFO: User found: tommyboy [in users.py:101]
2024-03-18 11:40:31,355 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 11:40:31,458 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 11:40:31,459 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 11:43:04,065 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 11:43:04,067 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 11:43:04,071 INFO: User found: tommyboy [in users.py:101]
2024-03-18 11:43:04,071 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 11:43:04,167 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 11:43:04,167 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 11:43:35,288 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 11:43:35,289 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 11:43:35,293 INFO: User found: tommyboy [in users.py:101]
2024-03-18 11:43:35,294 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 11:43:35,398 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 11:43:35,398 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 11:54:45,542 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 11:54:45,542 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 11:54:45,545 INFO: User found: tommyboy [in users.py:101]
2024-03-18 11:54:45,545 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 11:54:45,662 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 11:54:45,662 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 13:34:29,594 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-18 13:35:39,372 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 13:35:39,372 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 13:35:39,419 INFO: User found: tommyboy [in users.py:101]
2024-03-18 13:35:39,419 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 13:35:39,515 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 13:35:39,515 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 13:49:46,155 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 13:49:46,156 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 13:49:46,159 INFO: User found: tommyboy [in users.py:101]
2024-03-18 13:49:46,160 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 13:49:46,260 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 13:49:46,261 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 14:20:38,626 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 14:20:38,629 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 14:20:38,637 INFO: User found: tommyboy [in users.py:101]
2024-03-18 14:20:38,638 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 14:20:38,741 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 14:20:38,743 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 14:22:22,042 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 14:22:22,043 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 14:22:22,046 INFO: User found: tommyboy [in users.py:101]
2024-03-18 14:22:22,046 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 14:22:22,141 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 14:22:22,141 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 14:25:14,073 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 14:25:14,074 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 14:25:14,077 INFO: User found: tommyboy [in users.py:101]
2024-03-18 14:25:14,077 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 14:25:14,179 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 14:25:14,180 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 14:28:18,051 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 14:28:18,052 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 14:28:18,055 INFO: User found: tommyboy [in users.py:101]
2024-03-18 14:28:18,055 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 14:28:18,165 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 14:28:18,166 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 14:31:51,497 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 14:31:51,499 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 14:31:51,502 INFO: User found: tommyboy [in users.py:101]
2024-03-18 14:31:51,502 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 14:31:51,608 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 14:31:51,609 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 14:35:14,350 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 14:35:14,351 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 14:35:14,356 INFO: User found: tommyboy [in users.py:101]
2024-03-18 14:35:14,357 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 14:35:14,479 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 14:35:14,480 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 15:23:16,678 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 15:23:16,679 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 15:23:16,687 INFO: User found: tommyboy [in users.py:101]
2024-03-18 15:23:16,687 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 15:23:16,797 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 15:23:16,799 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 15:45:23,051 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 15:45:23,053 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 15:45:23,062 INFO: User found: tommyboy [in users.py:101]
2024-03-18 15:45:23,062 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 15:45:23,160 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 15:45:23,162 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 15:45:57,892 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 15:45:57,893 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 15:45:57,895 INFO: User found: tommyboy [in users.py:101]
2024-03-18 15:45:57,895 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 15:45:57,997 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 15:45:57,998 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-18 15:52:08,269 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-18 15:52:08,270 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-18 15:52:08,273 INFO: User found: tommyboy [in users.py:101]
2024-03-18 15:52:08,273 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-18 15:52:08,382 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-18 15:52:08,384 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 13:38:13,312 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-19 13:38:41,812 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 13:38:41,813 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 13:38:41,858 INFO: User found: tommyboy [in users.py:101]
2024-03-19 13:38:41,859 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 13:38:41,963 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 13:38:41,964 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 13:48:38,706 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 13:48:38,707 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 13:48:38,711 INFO: User found: tommyboy [in users.py:101]
2024-03-19 13:48:38,711 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 13:48:38,813 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 13:48:38,814 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 13:51:16,230 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 13:51:16,231 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 13:51:16,233 INFO: User found: tommyboy [in users.py:101]
2024-03-19 13:51:16,233 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 13:51:16,330 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 13:51:16,330 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 13:52:15,756 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 13:52:15,757 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 13:52:15,759 INFO: User found: tommyboy [in users.py:101]
2024-03-19 13:52:15,759 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 13:52:15,857 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 13:52:15,857 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 13:55:07,050 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 13:55:07,050 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 13:55:07,052 INFO: User found: tommyboy [in users.py:101]
2024-03-19 13:55:07,052 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 13:55:07,151 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 13:55:07,152 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 13:55:35,751 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 13:55:35,751 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 13:55:35,754 INFO: User found: tommyboy [in users.py:101]
2024-03-19 13:55:35,754 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 13:55:35,860 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 13:55:35,861 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 13:55:53,645 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 13:55:53,646 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 13:55:53,648 INFO: User found: tommyboy [in users.py:101]
2024-03-19 13:55:53,648 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 13:55:53,752 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 13:55:53,752 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 13:56:34,170 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 13:56:34,171 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 13:56:34,174 INFO: User found: tommyboy [in users.py:101]
2024-03-19 13:56:34,174 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 13:56:34,271 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 13:56:34,271 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 13:59:06,365 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 13:59:06,365 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 13:59:06,368 INFO: User found: tommyboy [in users.py:101]
2024-03-19 13:59:06,368 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 13:59:06,489 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 13:59:06,489 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 14:23:31,851 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 14:23:31,852 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 14:23:31,854 INFO: User found: tommyboy [in users.py:101]
2024-03-19 14:23:31,854 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 14:23:31,951 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 14:23:31,952 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 14:25:00,273 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 14:25:00,274 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 14:25:00,276 INFO: User found: tommyboy [in users.py:101]
2024-03-19 14:25:00,276 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 14:25:00,384 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 14:25:00,384 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 16:01:59,842 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-19 16:02:20,150 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 16:02:20,152 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 16:02:20,219 INFO: User found: tommyboy [in users.py:101]
2024-03-19 16:02:20,220 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 16:02:20,317 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 16:02:20,319 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 16:02:46,309 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 16:02:46,310 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 16:02:46,311 INFO: User found: tommyboy [in users.py:101]
2024-03-19 16:02:46,311 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 16:02:46,392 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 16:02:46,393 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 16:12:22,139 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 16:12:22,139 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 16:12:22,142 INFO: User found: tommyboy [in users.py:101]
2024-03-19 16:12:22,142 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 16:12:22,254 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 16:12:22,255 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 16:12:54,460 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 16:12:54,461 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 16:12:54,464 INFO: User found: tommyboy [in users.py:101]
2024-03-19 16:12:54,464 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 16:12:54,557 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 16:12:54,558 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 16:14:38,870 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 16:14:38,871 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 16:14:38,873 INFO: User found: tommyboy [in users.py:101]
2024-03-19 16:14:38,873 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 16:14:38,969 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 16:14:38,969 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 16:15:15,580 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 16:15:15,580 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 16:15:15,582 INFO: User found: tommyboy [in users.py:101]
2024-03-19 16:15:15,582 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 16:15:15,682 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 16:15:15,682 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 16:30:34,307 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 16:30:34,308 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 16:30:34,310 INFO: User found: tommyboy [in users.py:101]
2024-03-19 16:30:34,310 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 16:30:34,394 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 16:30:34,394 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 16:32:31,878 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 16:32:31,879 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 16:32:31,881 INFO: User found: tommyboy [in users.py:101]
2024-03-19 16:32:31,881 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 16:32:31,989 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 16:32:31,990 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 16:34:29,897 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 16:34:29,898 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 16:34:29,901 INFO: User found: tommyboy [in users.py:101]
2024-03-19 16:34:29,901 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 16:34:30,017 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 16:34:30,018 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 16:38:01,379 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 16:38:01,380 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 16:38:01,383 INFO: User found: tommyboy [in users.py:101]
2024-03-19 16:38:01,383 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 16:38:01,473 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 16:38:01,473 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 16:46:37,142 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 16:46:37,143 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 16:46:37,146 INFO: User found: tommyboy [in users.py:101]
2024-03-19 16:46:37,146 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 16:46:37,262 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 16:46:37,263 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 16:48:25,624 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-19 16:48:46,977 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 16:48:46,978 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 16:48:47,026 INFO: User found: tommyboy [in users.py:101]
2024-03-19 16:48:47,026 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 16:48:47,118 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 16:48:47,119 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 18:10:32,855 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-19 18:10:53,658 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 18:10:53,659 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 18:10:53,698 INFO: User found: tommyboy [in users.py:101]
2024-03-19 18:10:53,698 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 18:10:53,785 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 18:10:53,786 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 18:12:25,692 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 18:12:25,693 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 18:12:25,696 INFO: User found: tommyboy [in users.py:101]
2024-03-19 18:12:25,697 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 18:12:25,797 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 18:12:25,797 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 18:17:41,864 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-19 18:26:40,103 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 18:26:40,105 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 18:26:40,155 INFO: User found: tommyboy [in users.py:101]
2024-03-19 18:26:40,156 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 18:26:40,258 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 18:26:40,260 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 18:31:10,623 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 18:31:10,624 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 18:31:10,628 INFO: User found: tommyboy [in users.py:101]
2024-03-19 18:31:10,628 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 18:31:10,733 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 18:31:10,733 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-19 18:44:45,688 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-19 18:44:45,690 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-19 18:44:45,699 INFO: User found: tommyboy [in users.py:101]
2024-03-19 18:44:45,699 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-19 18:44:45,815 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-19 18:44:45,817 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 08:42:54,664 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 08:45:26,919 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 08:45:26,921 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 08:45:26,997 INFO: User found: tommyboy [in users.py:101]
2024-03-20 08:45:26,997 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 08:45:27,089 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 08:45:27,089 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 08:45:42,731 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 08:45:42,731 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 08:45:42,735 INFO: User found: tommyboy [in users.py:101]
2024-03-20 08:45:42,735 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 08:45:42,834 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 08:45:42,834 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 08:47:48,383 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 08:48:18,127 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 08:48:18,129 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 08:48:18,171 INFO: User found: tommyboy [in users.py:101]
2024-03-20 08:48:18,171 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 08:48:18,266 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 08:48:18,266 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 08:48:42,322 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 08:48:42,323 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 08:48:42,328 INFO: User found: tommyboy [in users.py:101]
2024-03-20 08:48:42,329 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 08:48:42,449 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 08:48:42,450 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 08:50:17,590 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 08:50:17,591 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 08:50:17,595 INFO: User found: tommyboy [in users.py:101]
2024-03-20 08:50:17,595 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 08:50:17,736 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 08:50:17,737 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 08:53:30,696 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 08:53:48,447 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 08:53:48,448 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 08:53:48,488 INFO: User found: tommyboy [in users.py:101]
2024-03-20 08:53:48,488 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 08:53:48,592 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 08:53:48,592 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 08:54:06,828 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 08:54:06,829 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 08:54:06,835 INFO: User found: tommyboy [in users.py:101]
2024-03-20 08:54:06,835 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 08:54:06,946 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 08:54:06,947 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 08:55:16,423 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 08:55:16,424 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 08:55:16,427 INFO: User found: tommyboy [in users.py:101]
2024-03-20 08:55:16,427 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 08:55:16,522 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 08:55:16,523 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 08:56:05,558 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 08:56:05,559 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 08:56:05,562 INFO: User found: tommyboy [in users.py:101]
2024-03-20 08:56:05,562 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 08:56:05,679 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 08:56:05,681 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 08:57:48,213 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 08:57:48,213 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 08:57:48,216 INFO: User found: tommyboy [in users.py:101]
2024-03-20 08:57:48,216 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 08:57:48,363 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 08:57:48,366 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 08:59:25,030 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 08:59:25,031 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 08:59:25,034 INFO: User found: tommyboy [in users.py:101]
2024-03-20 08:59:25,034 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 08:59:25,227 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 08:59:25,227 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 09:00:41,575 INFO: Printing the data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 09:00:41,576 INFO: Validation successful. Validated data: {'username': 'tommyboy', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 09:00:41,578 INFO: User found: tommyboy [in users.py:101]
2024-03-20 09:00:41,578 INFO: Attempting to validate password for user: tommyboy [in users.py:108]
2024-03-20 09:00:41,727 INFO: Login successful for user: tommyboy. Generating access token... [in users.py:116]
2024-03-20 09:00:41,727 INFO: Printing the response: <Response 486 bytes [200 OK]> [in users.py:129]
2024-03-20 09:06:34,912 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 09:06:34,913 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 09:06:34,915 INFO: User found: eminem [in users.py:101]
2024-03-20 09:06:34,915 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-20 09:06:34,988 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-20 09:06:34,989 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-20 09:11:32,150 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 09:12:48,475 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 09:13:12,856 ERROR: Exception on /api/blog/posts [POST] [in app.py:828]
Traceback (most recent call last):
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/routes/blogs.py", line 52, in post
    validated_data, errors = hf.validate_data(post_schema, data)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/helpers/helper_functions.py", line 20, in validate_data
    return schema.load(data), None
           ^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/marshmallow/schema.py", line 723, in load
    return self._do_load(
           ^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/marshmallow/schema.py", line 910, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'title': ['Missing data for required field.'], 'slug': ['Missing data for required field.'], 'username': ['Unknown field.'], 'password': ['Unknown field.']}
2024-03-20 09:19:56,413 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 09:20:51,617 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 09:22:19,966 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 09:22:19,967 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 09:22:20,000 INFO: User found: eminem [in users.py:101]
2024-03-20 09:22:20,000 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-20 09:22:20,083 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-20 09:22:20,084 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-20 09:24:09,117 ERROR: Exception on /api/blog/posts [POST] [in app.py:828]
Traceback (most recent call last):
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/donkeybetz_ai_crews/.venv/lib/python3.11/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/routes/blogs.py", line 62, in post
    generated_content = generate_content(user_id, f"{title}. {content}", index_name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/langchain_utils/agents/content_creator.py", line 27, in generate_content
    from langchain_utils.prompts.content_prompt import create_few_shot_prompt
ModuleNotFoundError: No module named 'langchain_utils.prompts'
2024-03-20 09:56:15,507 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 09:57:01,040 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 09:57:35,296 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 09:57:35,296 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 09:57:35,321 INFO: User found: eminem [in users.py:101]
2024-03-20 09:57:35,322 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-20 09:57:35,401 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-20 09:57:35,402 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
2024-03-20 09:58:14,050 ERROR: Exception on /api/blog/posts [POST] [in app.py:828]
Traceback (most recent call last):
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/routes/blogs.py", line 61, in post
    slug = bh.generate_unique_slug(title)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/helpers/blog_helpers.py", line 34, in generate_unique_slug
    while slug_exists(unique_slug):
          ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: slug_exists() missing 1 required positional argument: 'slug'
2024-03-20 09:59:47,751 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 10:01:33,556 ERROR: Exception on /api/blog/posts [GET] [in app.py:828]
Traceback (most recent call last):
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/.venv/lib/python3.11/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/routes/blogs.py", line 40, in get
    return jsonify([post.serialize() for post in posts]), 200
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/ai_donkeys/backend/routes/blogs.py", line 40, in <listcomp>
    return jsonify([post.serialize() for post in posts]), 200
                    ^^^^^^^^^^^^^^
AttributeError: 'Post' object has no attribute 'serialize'
2024-03-20 10:13:08,938 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
2024-03-20 10:13:19,840 INFO: Printing the data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:87]
2024-03-20 10:13:19,842 INFO: Validation successful. Validated data: {'username': 'eminem', 'password': 'Superuser1'} [in users.py:93]
2024-03-20 10:13:19,871 INFO: User found: eminem [in users.py:101]
2024-03-20 10:13:19,871 INFO: Attempting to validate password for user: eminem [in users.py:108]
2024-03-20 10:13:19,954 INFO: Login successful for user: eminem. Generating access token... [in users.py:116]
2024-03-20 10:13:19,955 INFO: Printing the response: <Response 485 bytes [200 OK]> [in users.py:129]
